###
GET http://localhost:5000/api/members

###
GET http://localhost:5000/api/members/5e91e379eb0e2c470cd8ee7a

###
GET http://localhost:5000/api/members/5e91eacb77b07d78b8f6432c

###
POST http://localhost:5000/api/members
content-type: application/json

{
    "name": "Pluto",
    "age": 22
}

###
PUT http://localhost:5000/api/members/5e91eacb77b07d78b8f6432c
content-type: application/json

{
    "name": "Poopy"
}

###
PATCH http://localhost:5000/api/members/5e91eacb77b07d78b8f6432c
content-type: application/json

{
    "name": "Poopy",
    "age": 21
}

###
DELETE http://localhost:5000/api/members/5e91eacb77b07d78b8f6432c


